version: "3"

services:
    api:
        container_name: api
        build: ./api
        ports:
            - "8000:8000"
        volumes:
            - ./code:/usr/src/server
        networks:
            - local-net

networks:
    local-net:
        driver: bridge
